from mcp.server.mcpserver import MCPServer

from tools.code_fixer import prepare_fix


server = MCPServer(
    name="fixer-mcp"
)


@server.tool()
def fix_code(fix_response: str) -> dict:
    """
    Extract and prepare corrected code generated by the Fixer Agent.
    """
    return prepare_fix(fix_response)


if __name__ == "__main__":
    server.run()